# -*- coding: utf-8 -*-

"""Convert SBGN-ML files generated by converting CellDesigner files with https://github.com/sbgn/cd2sbgnml.

Inspired by https://github.com/cannin/sbgn2sif.

Example SBGN-ML files can be found at:
- https://cannin.github.io/covid19-sbgn/
"""

from .convert import convert_sbgn
from .parse import parse_sbgn, parse_sbgn_url
