# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
# To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
# https://tox.readthedocs.io/en/latest/example/package.html
isolated_build = True

# These environments are run in order if you just use `tox`:
envlist =
    # always keep coverage-clean first
    coverage-clean
    # code formatters
    format
    # format-docs
    # Code quality assessment
    pyroma
    lint
    lint-markdown
    mypy
    # Documentation quality assurance
    docs-lint
    docstr-coverage
    docs-test
    # the actual tests
    py
    doctests
    # always keep coverage-report last
    coverage-report

[testenv]
description = Run unit and integration tests.
skip_install = true
allowlist_externals =
    uv
    uvx
commands =
    uvx --from rust-just just test

[testenv:coverage-clean]
description = Remove testing coverage artifacts.
commands =
    uvx --from rust-just just coverage-clean

[testenv:coverage-report]
commands =
    uvx --from rust-just just coverage-report

[testenv:doctests]
description = Test that documentation examples run properly.
commands =
    uvx --from rust-just just doctests

[testenv:treon]
description = Test that notebooks can be run to completion
commands =
    uvx --from rust-just just treon

[testenv:format]
description = Format the code.
commands =
    uvx --from rust-just just format

[testenv:format-docs]
description = Run documentation linters.
commands =
    uvx --from rust-just just format-docs

[testenv:format-markdown]
description = Run markdown formatter.
commands =
    uvx --from rust-just just format-markdown

[testenv:lint]
description = Check code quality using ruff and other tools.
commands =
    uvx --from rust-just just lint

[testenv:lint-markdown]
description = Check markdown is properly formatted.
commands =
    uvx --from rust-just just lint-markdown

[testenv:lint-justfile]
description = Check justfile is properly formatted.
commands =
    uvx --from rust-just just lint-justfile

[testenv:pyroma]
description = Check the metadata health of the project
commands =
    uvx --from rust-just just pyroma

[testenv:mypy]
description = Run the mypy tool to check static typing on the project.
commands =
    uvx --from rust-just just mypy

[testenv:docs-lint]
description = Run the doc8 tool to check the style of the RST files in the project docs.
commands =
    uvx --from rust-just just docs-lint

[testenv:docstr-coverage]
description = Run the docstr-coverage tool to check documentation coverage.
commands =
    uvx --from rust-just just docstr-coverage

[testenv:docs]
description = Build the documentation locally, allowing warnings.
commands =
    uvx --from rust-just just docs

[testenv:docs-test]
description = Test building the documentation in an isolated environment. Warnings are considered as errors via -W.
commands =
    uvx --from rust-just just docs-test

####################
# Deployment tools #
####################

[testenv:bumpversion]
description = Bump the version number
commands =
    uvx --from rust-just just bumpversion {posargs}

[testenv:bumpversion-release]
description = Remove the -dev tag from the version
commands =
    uvx --from rust-just just bumpversion-release

[testenv:build]
commands =
    uvx --from rust-just just build

[testenv:release]
description = Release the code to PyPI so users can pip install it, using credentials from keyring
commands =
    uvx --from rust-just just release

[testenv:release-via-env]
description = Release the code to PyPI so users can pip install it, using credentials from the environment.
commands =
    uvx --from rust-just just release-via-env
passenv =
    UV_PUBLISH_USERNAME
    UV_PUBLISH_PASSWORD

[testenv:finish]
description =
    Run a workflow that removes -dev from the version, creates a tagged release on GitHub,
    creates a release on PyPI, and bumps the version again.
passenv =
    HOME
allowlist_externals =
    uv
    uvx
    git
commands =
    uvx --from rust-just just finish

[testenv:testrelease]
description = Release the code to the test PyPI site
commands =
    uvx --from rust-just just test-release

[testenv:testfinish]
description =
    Run a workflow that removes -dev from the version, creates a tagged release on GitHub,
    creates a release on Test PyPI, and bumps the version again.
passenv =
    HOME
commands =
    uvx --from rust-just just test-finish
allowlist_externals =
    uv
    uvx
    git
